### ISSUE TITLE
Give Fam Exp for starred posts

### ISSUE THREAD

**Issue by WikiWikiWasp** [Games-Gamers/FamBot#1]
# Description
Need to apply exp to a user when their posts have been starred and sent to `#starboard`. 
First iteration can just award a static amount if starred. A future iteration can award exp for each star added.

# Suggestions
### One of two methods:
1. Watch for messages from `StarBot` and pull the user's name from the embed, then award exp using user lookup
2. Watch for ⭐ reactions on any message, like `StarBot` already does, then award from there, similar to the FAM emoji. 

1 takes a bit more work, but is more reliable and resistant to exp farming. 
2 is easy to implement given its similarity to existing functionality, but is susceptible to exp farming with ⭐ reaction spamming.

1 is probably the best method for now, unless obstacles make it more work than it's worth.

# Acceptance Criteria
- User is awarded `5 exp` when a post is starred.
- Can rank up the user if applicable

# Notes
Exp value awarded might be adjusted during or at a later date with xp balance. Especially if awarded per star.

**Comment by mulchbutler** [comment]
Is this already complete?
https://github.com/Games-Gamers/FamBot/blob/main/main.py#L80

**Comment by WikiWikiWasp** [comment]
Yea it seems like it lol closing issue then
