### ISSUE TITLE
Convert json 'database' into Redis database

### ISSUE THREAD

**Issue by WikiWikiWasp** [Games-Gamers/FamBot#18]
# Description
Currently, the experience, ranks, and titles for members are being stored and updated in the `users.json` file. 
This is a temporary solution while features are being developed and tested. 
We need to convert this "database" into a more sustainable and manageable database.

# Suggestions
- Redis DB

# Acceptance Criteria
- [ ] Database service chosen
- [ ] JSON file converted to a real database

---
# Notes

**Comment by mulchbutler** [comment]
@bossanova456 Did you ever finish or give up on this? Will Redis work or should we use a different database?
