### ISSUE TITLE
Host FamBot on Raspberry Pi

### ISSUE THREAD

**Issue by WikiWikiWasp** [Games-Gamers/FamBot#9]
# Description
I need to setup a Raspberry Pi to host FamBot.

# Suggestions
- get a raspberry pi kit for hosting
- get with @mulchbutler and/or @bossanova456 for help on setup

# Acceptance Criteria
- [x] Raspberry Pi kit acquired
- [x] Raspberry Pi configured
- [x] FamBot hosted on Raspberry Pi

---
# Notes
Raspberry Pi Kit I'm gettting: https://www.amazon.com/dp/B07V5JTMV9?psc=1&ref=ppx_yo2_dt_b_product_details
Will need a future issue for CI/CD configuration using github action or another service.

**Comment by mulchbutler** [comment]
If you have a Pi with Docker on it, #17 should get you pretty close to letting you run the app on the Pi

**Comment by mulchbutler** [comment]
We're live on a Pi!
